import os

# CONSTANTES DE RUTAS
DIR_BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR_DATA = os.path.join(DIR_BASE, "data")
DIR_ASSETS = os.path.join(DIR_BASE, "assets")
DIR_ASSETS_IMAGES = os.path.join(DIR_ASSETS, "images")
DIR_ASSETS_AUDIO = os.path.join(DIR_BASE, "media", "audio")

PATH_CONFIG_JSON = os.path.join(DIR_DATA, "config.json")

# ESTRUCTURA BIBLIA
LIBROS_BIBLIA = {
    "es": [
        "GÉNESIS", "ÉXODO", "LEVÍTICO", "NÚMEROS", "DEUTERONOMIO", "JOSUÉ", "JUECES", "RUT",
        "1 SAMUEL", "2 SAMUEL", "1 REYES", "2 REYES", "1 CRÓNICAS", "2 CRÓNICAS", "ESDRAS",
        "NEHEMÍAS", "ESTER", "JOB", "SALMOS", "PROVERBIOS", "ECLESIASTÉS", "CANTARES",
        "ISAÍAS", "JEREMÍAS", "LAMENTACIONES", "EZEQUIEL", "DANIEL", "OSEAS", "JOEL", "AMÓS",
        "ABDÍAS", "JONÁS", "MIQUEAS", "NAHÚM", "HABACUC", "SOFONÍAS", "HAGEO", "ZACARÍAS", "MALAQUÍAS",
        "MATEO", "MARCOS", "LUCAS", "JUAN", "HECHOS", "ROMANOS", "1 CORINTIOS", "2 CORINTIOS",
        "GÁLATAS", "EFESIOS", "FILIPENSES", "COLOSENSES", "1 TESALONICENSES", "2 TESALONICENSES",
        "1 TIMOTEO", "2 TIMOTEO", "TITO", "FILEMÓN", "HEBREOS", "SANTIAGO", "1 PEDRO", "2 PEDRO",
        "1 JUAN", "2 JUAN", "3 JUAN", "JUDAS", "APOCALIPSE"
    ],
    "en": [
        "GENESIS", "EXODUS", "LEVITICUS", "NUMBERS", "DEUTERONOMY", "JOSHUA", "JUDGES", "RUTH",
        "1 SAMUEL", "2 SAMUEL", "1 KINGS", "2 KINGS", "1 CHRONICLES", "2 CHRONICLES", "EZRA",
        "NEHEMIAH", "ESTHER", "JOB", "PSALMS", "PROVERBS", "ECCLESIASTES", "SONG OF SOLOMON",
        "ISAIAH", "JEREMIAH", "LAMENTATIONS", "EZEKIEL", "DANIEL", "HOSEA", "JOEL", "AMOS",
        "OBADIAH", "JONAH", "MICAH", "NAHUM", "HABAKKUK", "ZEPHANIAH", "HAGGAI", "ZECHARIAH", "MALACHI",
        "MATTHEW", "MARK", "LUKE", "JOHN", "ACTS", "ROMANS", "1 CORINTHIANS", "2 CORINTHIANS",
        "GALATIANS", "EPHESIANS", "PHILIPPIANS", "COLOSSIANS", "1 THESSALONIANS", "2 THESSALONIANS",
        "1 TIMOTHY", "2 TIMOTHY", "TITUS", "PHILEMON", "HEBREWS", "JAMES", "1 PETER", "2 PETER",
        "1 JOHN", "2 JOHN", "3 JOHN", "JUDE", "REVELATION"
    ],
    "fr": [
        "GENÈSE", "EXODE", "LÉVITIQUE", "NOMBRES", "DUTERONOME", "JOSUÉ", "JUGES", "RUTH",
        "1 SAMUEL", "2 SAMUEL", "1 ROIS", "2 ROIS", "1 CHRONIQUES", "2 CHRONIQUES", "ESDRAS",
        "NÉHÉMIE", "ESTHER", "JOB", "PSAUMES", "PROVERBES", "ECCLÉSIASTE", "CANTIQUE DES CANTIQUES",
        "ÉSAÏE", "JÉRÉMIE", "LAMENTATIONS", "ÉZÉCHIEL", "DANIEL", "OSÉE", "JOËL", "AMOS",
        "ABD IAS", "JONAS", "MICHÉE", "NAHUM", "HABACUC", "SOPHONIE", "AGGÉE", "ZACHARIE", "MALACHIE",
        "MATTHIEU", "MARC", "LUC", "JEAN", "ACTES", "ROMAINS", "1 CORINTHIENS", "2 CORINTHIENS",
        "GALATES", "ÉPHÉSIENS", "PHILIPPIENS", "COLOSSIENS", "1 THESSALONICIENS", "2 THESSALONICIENS",
        "1 TIMOTHÉE", "2 TIMOTHÉE", "TITE", "PHILÉMON", "HÉBREUX", "JACQUES", "1 PIERRE", "2 PIERRE",
        "1 JEAN", "2 JEAN", "3 JEAN", "JUDE", "APOCALYPSE"
    ],
    "it": [
        "GENESI", "ESODO", "LEVITICO", "NUMERI", "DEUTERONOMIO", "GIOSUE", "GIUDICI", "RUT",
        "1 SAMUELE", "2 SAMUELE", "1 RE", "2 RE", "1 CRONACHE", "2 CRONACHE", "ESDRA",
        "NEEMIA", "ESTER", "GIOBBE", "SALMI", "PROVERBI", "ECCLESIASTE", "CANTO DEI CANTI",
        "ISAIA", "GEREMIA", "LAMENTAZIONI", "EZECHIELE", "DANIELE", "OSEA", "GIOELE", "AMOS",
        "ABDIA", "GIONA", "MICHEA", "NAUM", "ABACUC", "SOFONIA", "AGGEO", "ZACCARIA", "MALACHIA",
        "MATTEO", "MARCO", "LUCA", "GIOVANNI", "ATTI", "ROMANI", "1 CORINZI", "2 CORINZI",
        "GALATI", "EFESINI", "FILIPPESI", "COLOSSESI", "1 TESSALONICESI", "2 TESSALONICESI",
        "1 TIMOTEO", "2 TIMOTEO", "TITO", "FILEMONE", "EBREI", "GIACOMO", "1 PIETRO", "2 PIETRO",
        "1 GIOVANNI", "2 GIOVANNI", "3 GIOVANNI", "GIUDA", "APOCALISSE"
    ],
    "por": [
        "GÊNESIS", "ÊXODO", "LEVÍTICO", "NÚMEROS", "DEUTERONÔMIO", "JOSUÉ", "JUÍZES", "RUTE",
        "1 SAMUEL", "2 SAMUEL", "1 REIS", "2 REIS", "1 CRÔNICAS", "2 CRÔNICAS", "ESDRAS",
        "NEEMIAS", "ESTER", "JÓ", "SALMOS", "PROVÉRBIOS", "ECLESIASTES", "CÂNTICO DOS CÂNTICOS",
        "ISAÍAS", "JEREMIAS", "LAMENTAÇÕES", "EZEQUIEL", "DANIEL", "OSÉIAS", "JOEL", "AMÓS",
        "OBADIAS", "JONAS", "MIQUÉIAS", "NAUM", "HABACUQUE", "SOFONIAS", "AGEU", "ZACARIAS", "MALAQUIAS",
        "MATEUS", "MARCOS", "LUCAS", "JOÃO", "ATOS", "ROMANOS", "1 CORÍNTIOS", "2 CORÍNTIOS",
        "GÁLATAS", "EFÉSIOS", "FILIPENSES", "COLOSSENSES", "1 TESSALONICENSES", "2 TESSALONICENSES",
        "1 TIMÓTEO", "2 TIMÓTEO", "TITO", "FILEMON", "HEBREUS", "TIAGO", "1 PEDRO", "2 PEDRO",
        "1 JOÃO", "2 JOÃO", "3 JOÃO", "JUDAS", "APOCALIPSE"
    ]
}

CAPITULOS_POR_LIBRO = [
    50, 40, 27, 36, 34, 24, 21, 4, 31, 24, 22, 25, 29, 36, 10, 13, 10, 42, 150, 31, 12, 8,
    66, 52, 5, 48, 12, 14, 3, 9, 1, 4, 7, 3, 3, 3, 2, 14, 4, 28, 16, 24, 21, 28, 16, 16, 13,
    6, 6, 4, 4, 5, 3, 6, 4, 3, 1, 13, 5, 5, 3, 5, 1, 1, 1, 22
]

NOMBRES_BIBLIAS = {
    "es": "Reina-Valera 1960",
    "en": "King James Version",
    "fr": "Louis Segond 1910",
    "it": "Riveduta 1927",
    "por": "João Ferreira de Almeida"
}

DICCIONARIO_UI = {
    "es": {
        "splash_file": "Presentador_Bíblico_ES.jpeg",
        "titulo_ventana": "Versículo del Día",
        "trigger_menu": "MENÚ",
        "leer_entero": "Leer capítulo entero",
        "btn_cambiar_fondo": "🖼️ Cambiar paisaje",
        "btn_anterior": "◄ Anterior",
        "btn_siguiente": "Nuevo ►",
        "nav_cap_ant": "◄ Cap. Anterior",
        "nav_cap_sig": "Cap. Siguiente ►",
        "btn_renglones_si": "Renglones: ☑ Sí",
        "btn_renglones_no": "Renglones: ☐ No",
        "pista_clic": "(Haz clic para cambiar)",
        "at": "ANTIGUO TESTAMENTO",
        "nt": "NUEVO TESTAMENTO",
        "volver": "Volver (Esc)",
        "menu_musica_on": "🔊 Activar música de fondo",
        "menu_musica_off": "🔇 Detener música de fondo",
        "menu_paisaje": "🖼️ Opciones de paisaje",
        "menu_exportar": "✉️ Compartir postal (WhatsApp / Telegram)",
        "menu_buscador": "🔍 Buscador de frases",
        "menu_leer_biblia": "📖 Leer la Biblia entera",
        "menu_idioma": "🌐 Cambiar idioma",
        "menu_sabias_que": "💡 ¿Qué ofrece la app?",
        "menu_info": "ℹ️ Información sobre la app",
        "btn_salir": "✕ Salir de la app",
        "opciones_paisaje": "Opciones de paisaje",
        "paisaje_cambiar": "Cambiar paisaje ahora",
        "paisaje_mantener": "Mantener paisaje actual",
        "paisaje_sin": "Pantalla sin paisaje (Modo oscuro)",
        "cambiar_idioma": "Cambiar idioma",
        "info_tit": "PRESENTADOR BÍBLICO MULTILENGUAJE",
        "info_body": "Versículo diario y Biblia disponible.\n\nIdiomas soportados: Español, Inglés, Francés, Italiano y Portugués.",
        "sabias_que_tit": "💡 ¿QUÉ OFRECE LA APP?",
        "sabias_que_body": "• Lectura e inspiración diaria con pasaje automático de versículos.\n\n\n• Biblia entera integrada para lectura y consulta rápida por capítulos.\n\n\n• Música de fondo relajante y hermosos paisajes en alta resolución.\n\n\n• Buscador inteligente de frases y palabras clave.\n\n\n• Generador de postales personalizadas para compartir en WhatsApp y Telegram.\n\n\n• Soporte multilenguaje completo en 5 idiomas.",
        "btn_aceptar": "Aceptar",
        "compartir_tit": "COMPARTIR POSTAL",
        "compartir_msg": "¡Imagen copiada al portapapeles!\nSelecciona el destino y pega con Ctrl + V",
        "busc_titulo": "BUSCADOR DE FRASES",
        "busc_frase": "Frase a buscar:",
        "busc_btn_buscar": "BUSCAR",
        "busc_exacta": "Palabra exacta",
        "busc_pauta": "Por favor, haz doble clic en un resultado para abrir el capítulo entero.",
        "busc_buscando": "Buscando coincidencias en el texto...",
        "busc_cero_coincidencias": "Se encontraron 0 coincidencias",
        "busc_no_encontrado": "No se encontraron versículos con esa frase.",
        "busc_coincidencias": "Se encontraron {} coincidencias",
        "busc_error_archivo": "No se encontró la base de datos para {}",
        "paisaje_borrar": "🗑️ Borrar este paisaje de la galería",
        "conf_borrar_tit": "CONFIRMAR ELIMINACIÓN",
        "conf_borrar_msg": "¿Querés borrar definitivamente el archivo de esta imagen del disco duro?",
        "btn_si_borrar": "SÍ, BORRAR",
        "btn_cancelar": "CANCELAR",
        "bienvenida_tit": "¡BIENVENIDO A PRESENTADOR BÍBLICO!",
        "bienvenida_body": (
            "Gracias por instalar la aplicación.\n\n"
            "Te sugerimos explorar el MENÚ para descubrir "
            "la Biblia completa, cambiar de idioma, personalizar paisajes "
            "y compartir tus postales favoritas.")
           
    },
    "en": {
        "splash_file": "Presentador_Bíblico_EN.jpeg",
        "titulo_ventana": "Verse of the Day",
        "trigger_menu": "MENU",
        "leer_entero": "Read whole chapter",
        "btn_cambiar_fondo": "🖼️ Change landscape",
        "btn_anterior": "◄ Previous",
        "btn_siguiente": "Next ►",
        "nav_cap_ant": "◄ Prev. Chap.",
        "nav_cap_sig": "Next Chap. ►",
        "btn_renglones_si": "Lines: ☑ Yes",
        "btn_renglones_no": "Lines: ☐ No",
        "pista_clic": "(Click to change)",
        "at": "OLD TESTAMENT",
        "nt": "NEW TESTAMENT",
        "volver": "Back (Esc)",
        "menu_musica_on": "🔊 Enable background music",
        "menu_musica_off": "🔇 Stop background music",
        "menu_paisaje": "🖼️ Landscape options",
        "menu_exportar": "✉️ Share postcard (WhatsApp / Telegram)",
        "menu_buscador": "🔍 Phrase search engine",
        "menu_leer_biblia": "📖 Read the entire Bible",
        "menu_idioma": "🌐 Change language",
        "menu_sabias_que": "💡 What does the app offer?",
        "menu_info": "ℹ️ About the app",
        "btn_salir": "✕ Exit app",
        "opciones_paisaje": "Landscape options",
        "paisaje_cambiar": "Change landscape now",
        "paisaje_mantener": "Keep current landscape",
        "paisaje_sin": "Dark mode (no landscape)",
        "cambiar_idioma": "Change language",
        "info_tit": "MULTILINGUAL BIBLE PRESENTATION",
        "info_body": "Daily verse and full Bible available.\n\nSupported Languages: Spanish, English, French, Italian, and Portuguese.",
        "sabias_que_tit": "💡 WHAT DOES THE APP OFFER?",
        "sabias_que_body": "• Daily reading and inspiration with automatic verse switching.\n\n\n• Entire integrated Bible for quick reading and chapter search.\n\n\n• Relaxing background music and beautiful high-resolution landscapes.\n\n\n• Smart search engine for phrases and key words.\n\n\n• Custom postcard generator to share on WhatsApp and Telegram.\n\n\n• Complete multilingual support in 5 languages.",
        "btn_aceptar": "Accept",
        "compartir_tit": "SHARE POSTCARD",
        "compartir_msg": "Image copied to clipboard!\nSelect destination and paste with Ctrl + V",
        "busc_titulo": "PHRASE SEARCH ENGINE",
        "busc_frase": "Search phrase:",
        "busc_btn_buscar": "SEARCH",
        "busc_exacta": "Exact word",
        "busc_pauta": "Please double-click a result to open the full chapter.",
        "busc_buscando": "Searching matches in text...",
        "busc_cero_coincidencias": "Found 0 matches",
        "busc_no_encontrado": "No verses found with that phrase.",
        "busc_coincidencias": "Found {} matches",
        "busc_error_archivo": "Database file not found for {}",
        "paisaje_borrar": "🗑️ Delete this landscape from gallery",
        "conf_borrar_tit": "CONFIRM DELETE",
        "conf_borrar_msg": "Do you want to permanently delete this image file from disk?",
        "btn_si_borrar": "YES, DELETE",
        "btn_cancelar": "CANCEL",
        "bienvenida_tit": "WELCOME TO BIBLICAL PRESENTER!",
        "bienvenida_body": (
            "Thank you for installing the application.\n\n"
            "We suggest exploring the MENU to discover "
            "the complete Bible, change languages, customize landscapes, "
            "and share your favorite verse postals.")
    },
    "fr": {
        "splash_file": "Presentador_Bíblico_FR.png",
        "titulo_ventana": "Verset du Jour",
        "trigger_menu": "MENU",
        "leer_entero": "Lire le chapitre entier",
        "btn_cambiar_fondo": "🖼️ Changer de paysage",
        "btn_anterior": "◄ Précédent",
        "btn_siguiente": "Suivant ►",
        "nav_cap_ant": "◄ Chap. Préc.",
        "nav_cap_sig": "Chap. Suiv. ►",
        "btn_renglones_si": "Lignes : ☑ Oui",
        "btn_renglones_no": "Lignes : ☐ Non",
        "pista_clic": "(Cliquez pour changer)",
        "at": "ANCIEN TESTAMENT",
        "nt": "NOUVEAU TESTAMENT",
        "volver": "Retour (Esc)",
        "menu_musica_on": "🔊 Activer la musique de fond",
        "menu_musica_off": "🔇 Arrêter la musique de fond",
        "menu_paisaje": "🖼️ Options de paysage",
        "menu_exportar": "✉️ Partager carte (WhatsApp / Telegram)",
        "menu_buscador": "🔍 Moteur de recherche de phrases",
        "menu_leer_biblia": "📖 Lire toute la Bible",
        "menu_idioma": "🌐 Changer de langue",
        "menu_sabias_que": "💡 Que propose l'application ?",
        "menu_info": "ℹ️ À propos de l'application",
        "btn_salir": "✕ Quitter l'application",
        "opciones_paisaje": "Options de paysage",
        "paisaje_cambiar": "Changer de paysage maintenant",
        "paisaje_mantener": "Conserver le paysage actuel",
        "paisaje_sin": "Mode sombre (sans paysage)",
        "cambiar_idioma": "Changer de langue",
        "info_tit": "PRÉSENTATION BIBLIQUE MULTILINGUE",
        "info_body": "Verset quotidien et Bible disponible.\n\nLangues prises en charge : espagnol, anglais, français, italien et portugais.",
        "sabias_que_tit": "💡 QUE PROPOSE L'APPLICATION ?",
        "sabias_que_body": "• Lecture et inspiration quotidiennes avec défilement automatique des versets.\n\n\n• Bible entière intégrée para une lecture et consultation rapide par chapitres.\n\n\n• Musique de fond relaxante et magnifiques paysages haute résolution.\n\n\n• Moteur de recherche intelligent de phrases et mots-clés.\n\n\n• Générateur de cartes personnalisées à partager sur WhatsApp et Telegram.\n\n• Support multilingue complet en 5 langues.",
        "btn_aceptar": "Accepter",
        "compartir_tit": "PARTAGER CARTE",
        "compartir_msg": "Image copiée dans le presse-papiers !\nSélectionnez la destination et collez avec Ctrl + V",
        "busc_titulo": "MOTEUR DE RECHERCHE DE PHRASES",
        "busc_frase": "Phrase à chercher :",
        "busc_btn_buscar": "CHERCHER",
        "busc_exacta": "Mot exact",
        "busc_pauta": "Veuillez double-cliquer sur un résultat pour ouvrir le chapitre entier.",
        "busc_buscando": "Recherche de correspondances...",
        "busc_cero_coincidencias": "0 correspondance trouvée",
        "busc_no_encontrado": "Aucun verset trouvé avec cette phrase.",
        "busc_coincidencias": "{} correspondances trouvées",
        "busc_error_archivo": "Fichier de base de données introuvable pour {}",
        "paisaje_borrar": "🗑️ Supprimer ce paysage de la galerie",
        "conf_borrar_tit": "CONFIRMER LA SUPPRESSION",
        "conf_borrar_msg": "Voulez-vous supprimer définitivement ce fichier image du disque ?",
        "btn_si_borrar": "OUI, SUPPRIMER",
        "btn_cancelar": "ANNULER",
        "bienvenida_tit": "BIENVENUE SUR LE PRÉSENTATEUR BIBLIQUE!",
        "bienvenida_body": (
            "Merci d'avoir installé l'application.\n\n"
            "Nous vous suggérons d'explorer le MENU pour découvrir "
            "la Bible complète, changer de langue, personnaliser les paysages "
            "et partager vos cartes versets préférées.")
    },
    "it": {
        "splash_file": "Presentador_Bíblico_IT.png",
        "titulo_ventana": "Versetto del Giorno",
        "trigger_menu": "MENU",
        "leer_entero": "Leggi l'intero capitolo",
        "btn_cambiar_fondo": "🖼️ Cambia paesaggio",
        "btn_anterior": "◄ Precedente",
        "btn_siguiente": "Nuovo ►",
        "nav_cap_ant": "◄ Cap. Prec.",
        "nav_cap_sig": "Cap. Succ. ►",
        "btn_renglones_si": "Righe: ☑ Sì",
        "btn_renglones_no": "Righe: ☐ No",
        "pista_clic": "(Fai clic per cambiare)",
        "at": "VECCHIO TESTAMENTO",
        "nt": "NUOVO TESTAMENTO",
        "volver": "Indietro (Esc)",
        "menu_musica_on": "🔊 Attiva musica di sottofondo",
        "menu_musica_off": "🔇 Disattiva musica di sottofondo",
        "menu_paisaje": "🖼️ Opzioni paesaggio",
        "menu_exportar": "✉️ Condividi cartolina (WhatsApp / Telegram)",
        "menu_buscador": "🔍 Motore di ricerca frasi",
        "menu_leer_biblia": "📖 Leggi l'intera Bibbia",
        "menu_idioma": "🌐 Cambia lingua",
        "menu_sabias_que": "💡 Cosa offre l'app?",
        "menu_info": "ℹ️ Informazioni sull'app",
        "btn_salir": "✕ Esci dall'app",
        "opciones_paisaje": "Opzioni paesaggio",
        "paisaje_cambiar": "Cambia paesaggio ora",
        "paisaje_mantener": "Mantieni paesaggio attuale",
        "paisaje_sin": "Modalità scura (senza paesaggio)",
        "cambiar_idioma": "Cambia lingua",
        "info_tit": "PRESENTAZIONE BIBLICA MULTILINGUE",
        "info_body": "Sviluppato per la meditazione e la lettura delle Scritture.\n\nLingue supportate: spagnolo, inglese, francese, italiano e portoghese.",
        "sabias_que_tit": "💡 COSA OFFRE L'APP?",
        "sabias_que_body": "Versículo diário e Bíblia disponível.\n\n\n• Intera Bibbia integrata per una rapida lettura e consultazione per capitoli.\n\n\n• Musica di sottofondo rilassante e bellissimi paesaggi ad alta risoluzione.\n\n\n• Motore di ricerca intelligente per frasi e parole chiave.\n\n\n• Generatore di cartoline personalizzate da condividere su WhatsApp e Telegram.\n\n• Supporto multilingue completo in 5 lingue.",
        "btn_aceptar": "Accetta",
        "compartir_tit": "CONDIVIDI CARTOLINA",
        "compartir_msg": "Immagine copiata negli appunti!\nSeleziona la destinazione e incolla con Ctrl + V",
        "busc_titulo": "MOTORE DI RICERCA FRASI",
        "busc_frase": "Frase da cercare:",
        "busc_btn_buscar": "CERCA",
        "busc_exacta": "Parola esatta",
        "busc_pauta": "Fai doppio clic su un risultato per aprire l'intero capitolo.",
        "busc_buscando": "Ricerca corrispondenze nel testo...",
        "busc_cero_coincidencias": "Trovate 0 corrispondenze",
        "busc_no_encontrado": "Nessun versetto trovato con quella frase.",
        "busc_coincidencias": "Trovate {} corrispondenze",
        "busc_error_archivo": "File di database non trovato per {}",
        "paisaje_borrar": "🗑️ Elimina questo paesaggio dalla galleria",
        "conf_borrar_tit": "CONFERMA ELIMINAZIONE",
        "conf_borrar_msg": "Vuoi eliminare definitivamente questo file immagine dal disco?",
        "btn_si_borrar": "SÌ, ELIMINA",
        "btn_cancelar": "ANNULLA",
        "bienvenida_tit": "BENVENUTO IN PRESENTATORE BIBLICO!",
        "bienvenida_body": (
            "Grazie per aver installato l'applicazione.\n\n"
            "Ti suggeriamo di esplorare il MENU per scoprire "
            "la Bibbia completa, cambiare lingua, personalizzare i paesaggi "
            "e condividere le tue immagini preferite.")
    },
    "por": {
        "splash_file": "Presentador_Bíblico_POR.jpeg",
        "titulo_ventana": "Versículo do Dia",
        "trigger_menu": "MENU",
        "leer_entero": "Ler capítulo inteiro",
        "btn_cambiar_fondo": "🖼️ Mudar paisagem",
        "btn_anterior": "◄ Anterior",
        "btn_siguiente": "Novo ►",
        "nav_cap_ant": "◄ Cap. Ant.",
        "nav_cap_sig": "Cap. Seg. ►",
        "btn_renglones_si": "Linhas: ☑ Sim",
        "btn_renglones_no": "Linhas: ☐ Não",
        "pista_clic": "(Clique para mudar)",
        "at": "ANTIGO TESTAMENTO",
        "nt": "NOVO TESTAMENTO",
        "volver": "Voltar (Esc)",
        "menu_musica_on": "🔊 Ativar música de fundo",
        "menu_musica_off": "🔇 Parar música de fundo",
        "menu_paisaje": "🖼️ Opções de paisagem",
        "menu_exportar": "✉️ Compartilhar postal (WhatsApp / Telegram)",
        "menu_buscador": "🔍 Pesquisar frases",
        "menu_leer_biblia": "📖 Ler a Bíblia inteira",
        "menu_idioma": "🌐 Mudar idioma",
        "menu_sabias_que": "💡 O que o aplicativo oferece?",
        "menu_info": "ℹ️ Sobre o aplicativo",
        "btn_salir": "✕ Sair do aplicativo",
        "opciones_paisaje": "Opções de paisagem",
        "paisaje_cambiar": "Mudar paisagem agora",
        "paisaje_mantener": "Manter paisagem atual",
        "paisaje_sin": "Modo escuro (sem paisagem)",
        "cambiar_idioma": "Mudar idioma",
        "info_tit": "APRESENTAÇÃO BÍBLICA MULTILÍNGUE",
        "info_body": "Versículo diário e Bíblia disponível.\n\nIdiomas suportados: Espanhol, Inglês, Francês, Italiano e Português.",
        "sabias_que_tit": "💡 O QUE O APLICATIVO OFERECE?",
        "sabias_que_body": "• Leitura e inspiração diária com passagem automática de versículos.\n\n\n• Bíblia inteira integrada para leitura e consulta rápida por capítulos.\n\n\n• Música de fundo relaxante e belas paisagens em alta resolução.\n\n\n• Buscador inteligente de frases e palavras-chave.\n\n\n• Gerador de postais personalizados para compartilhar no WhatsApp e Telegram.\n\n\n• Suporte multilíngue completo em 5 idiomas.",
        "btn_aceptar": "Aceitar",
        "compartir_tit": "COMPARTILHAR POSTAL",
        "compartir_msg": "Imagem copiada para a área de transferência!\nSelecione o destino e cole com Ctrl + V",
        "busc_titulo": "MOTEUR DE PESQUISA DE FRASES",
        "busc_frase": "Frase para pesquisar:",
        "busc_btn_buscar": "PESQUISAR",
        "busc_exacta": "Palavra exata",
        "busc_pauta": "Clique duas vezes em um resultado para abrir o capítulo inteiro.",
        "busc_buscando": "Pesquisando correspondências...",
        "busc_cero_coincidencias": "Encontradas 0 correspondências",
        "busc_no_encontrado": "Nenhum versículo encontrado com essa frase.",
        "busc_coincidencias": "Encontradas {} correspondências",
        "busc_error_archivo": "Arquivo de banco de dados não encontrado para {}",
        "paisaje_borrar": "🗑️ Excluir esta paisagem da galeria",
        "conf_borrar_tit": "CONFIRMAR EXCLUSÃO",
        "conf_borrar_msg": "Deseja excluir permanentemente este arquivo de imagem do disco?",
        "btn_si_borrar": "SIM, EXCLUIR",
        "btn_cancelar": "CANCELAR",
        "bienvenida_tit": "BEM-VINDO AO APRESENTADOR BÍBLICO!",
        "bienvenida_body": (
            "Obrigado por instalar a aplicação.\n\n"
            "Sugerimos explorar o MENU para descobrir "
            "a Bíblia completa, alterar idiomas, personalizar paisagens "
            "e compartilhar suas postagens favoritas.")
    }
}
